#!/usr/bin/env python
import argparse
from argparse import ArgumentParser, FileType

def main(arguments):
    parser = ArgumentParser()
    parser.add_argument(
        "speakers_file",
        type=FileType("r", encoding="utf-8"),
        help="File with one speaker per line as generated by get_speakers.py"
    )
    parser.add_argument(
        "phonemes_file",
        type=FileType("r", encoding="utf-8"),
        help="File with phoneme transcriptions in each line, corresponding to speakers_file"
    )
    parser.add_argument(
        "phonemes_with_speakers_file",
        type=FileType("w", encoding="utf-8"),
        help="Output file for phoneme sequences with speaker information for SCTK alignment"
    )
    args = parser.parse_args(arguments)

    with args.speakers_file as speakers_file, args.phonemes_file as phonemes_file, args.phonemes_with_speakers_file as out_file:
        for phonemes, speakers in zip(phonemes_file, speakers_file):
            out_file.write(f"{phonemes.strip()} ({speakers.strip()})\n")


if __name__ == '__main__':
    import sys

    main(sys.argv[1:])
